package tests.creator;

import com.microsoft.playwright.Page;
import org.testng.Assert;
import org.testng.annotations.Test;
import pages.common.BaseTestClass;
import pages.creator.CreatorRegistrationPage;
import testdata.CreatorRegistrationData;
import utils.TestDataManager;

/**
 * Tests creator registration flow.
 * Test data is generated by CreatorRegistrationData.
 * Username is saved via TestDataManager for downstream tests.
 */
public class CreatorRegistrationTest extends BaseTestClass {

    @Test(
        priority = 1,
        description = "Complete creator registration with dynamically generated data",
        groups = {"registration.completed"}
    )
    public void testCreatorRegistration() {
        // Generate all test data
        CreatorRegistrationData data = CreatorRegistrationData.generate();

        // Execute registration flow
        CreatorRegistrationPage registrationPage = new CreatorRegistrationPage(page);
        registrationPage.completeRegistrationFlow(
            data.name,
            data.username,
            data.firstName,
            data.lastName,
            data.dob,
            data.email,
            data.password,
            data.phone,
            data.instagramUrl,
            data.gender,
            data.contentTypes,
            data.subscriptionPrice,
            data.identityPath,
            data.selfiePath
        );

        // Verify final step is displayed
        Assert.assertTrue(
            registrationPage.isFinalStepVisible(),
            "Final step page not displayed after registration"
        );

        // Click Continue and verify WhatsApp Web popup opens
        Page whatsAppPopup = registrationPage.clickContinueAndWaitForWhatsApp();
        Assert.assertTrue(
            whatsAppPopup.url().contains("web.whatsapp.com") || whatsAppPopup.url().contains("wa.me"),
            "Expected WhatsApp Web redirect but got: " + whatsAppPopup.url()
        );
        whatsAppPopup.close();

        // Share username with dependent tests
        TestDataManager.saveCreatorUsername(data.username);
    }
}
