package tests.creator;

import org.testng.Assert;
import org.testng.annotations.Test;
import pages.common.BaseTestClass;
import pages.creator.CreatorRegistrationPage;
import testdata.CreatorRegistrationData;
import utils.TestDataManager;

/**
 * Tests creator registration flow.
 * Test data is generated by CreatorRegistrationData.
 * Username is saved via TestDataManager for downstream tests.
 */
public class CreatorRegistrationTest extends BaseTestClass {

    @Test(
        priority = 1,
        description = "Complete creator registration with dynamically generated data",
        groups = {"registration.completed"}
    )
    public void testCreatorRegistration() {
        // Generate all test data
        CreatorRegistrationData data = CreatorRegistrationData.generate();

        // Execute registration flow
        CreatorRegistrationPage registrationPage = new CreatorRegistrationPage(page);
        registrationPage.completeRegistrationFlow(
            data.name,
            data.username,
            data.firstName,
            data.lastName,
            data.dob,
            data.email,
            data.password,
            data.phone,
            data.instagramUrl,
            data.gender,
            data.contentTypes,
            data.subscriptionPrice,
            data.identityPath,
            data.selfiePath
        );

        // Verify success
        Assert.assertTrue(
            registrationPage.isFinalConfirmationVisible(),
            "Registration confirmation not displayed"
        );

        // Share username with dependent tests
        TestDataManager.saveCreatorUsername(data.username);
    }
}
